## 方針

➀3桁×3桁の積を全パターン算出する  
➁➀を降順にソートする  
➂大きい数値から回文数に当たるまで探索する．

## インポート

In [1]:
import numpy as np
import math

## 回文数を判定する関数

In [2]:
def is_palindromic_number(num):
# num...数値.回文数かを判定したい数字を入力する．
    str_num = num.astype(str)
    loop_num = math.floor(len(str_num)/2)
    
    for i in range(loop_num):
        if str_num[i] != str_num[-1*(i + 1)]:
            return False
    
    return True

## 3桁の数値をinput_valに格納する

In [3]:
input_arr = np.arange(100,1000)
print(input_arr)

[100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117
 118 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135
 136 137 138 139 140 141 142 143 144 145 146 147 148 149 150 151 152 153
 154 155 156 157 158 159 160 161 162 163 164 165 166 167 168 169 170 171
 172 173 174 175 176 177 178 179 180 181 182 183 184 185 186 187 188 189
 190 191 192 193 194 195 196 197 198 199 200 201 202 203 204 205 206 207
 208 209 210 211 212 213 214 215 216 217 218 219 220 221 222 223 224 225
 226 227 228 229 230 231 232 233 234 235 236 237 238 239 240 241 242 243
 244 245 246 247 248 249 250 251 252 253 254 255 256 257 258 259 260 261
 262 263 264 265 266 267 268 269 270 271 272 273 274 275 276 277 278 279
 280 281 282 283 284 285 286 287 288 289 290 291 292 293 294 295 296 297
 298 299 300 301 302 303 304 305 306 307 308 309 310 311 312 313 314 315
 316 317 318 319 320 321 322 323 324 325 326 327 328 329 330 331 332 333
 334 335 336 337 338 339 340 341 342 343 344 345 34

## 3桁×3桁全パターンを算出する．input_valを列ベクトルと行ベクトルの両方用意し，列×行を実行する．

In [4]:
matrix = np.dot(input_arr[:, np.newaxis], input_arr[np.newaxis, :])
print(matrix)

[[ 10000  10100  10200 ...  99700  99800  99900]
 [ 10100  10201  10302 ... 100697 100798 100899]
 [ 10200  10302  10404 ... 101694 101796 101898]
 ...
 [ 99700 100697 101694 ... 994009 995006 996003]
 [ 99800 100798 101796 ... 995006 996004 997002]
 [ 99900 100899 101898 ... 996003 997002 998001]]


## 行列を1つのアレイに変換し，要素を降順にソートする．

In [5]:
arr = matrix.flatten()
arr = np.sort(arr)[::-1]
print(arr)

[998001 997002 997002 ...  10100  10100  10000]


## 要素を取り出して，回文数か判定する．

In [6]:
for num in arr:
    if is_palindromic_number(num) is True:
        ans = num
        break

## 答え

In [7]:
print(ans)

906609
